/*
 *  INDIAN STATES AND UNION TERITOIRES ENUM TABLE
 */
CREATE TABLE STATES_AND_UT_ENUM (
	ID INT(2) NOT NULL,
	STATE_OR_UT_CODE VARCHAR(2) NOT NULL,
	STATE_OR_UT_NAME VARCHAR(50) NOT NULL,
 CONSTRAINT STATES_AND_UT_ENUM_PK PRIMARY KEY (ID)
);
ALTER TABLE STATES_AND_UT_ENUM MODIFY COLUMN ID INT(2) AUTO_INCREMENT;
ALTER TABLE STATES_AND_UT_ENUM AUTO_INCREMENT=1;

CREATE TABLE STATUTORY_MASTER_ENUM (
	ID INT(2) NOT NULL,
	ITEM VARCHAR(25) NOT NULL,
	CONSTRAINT STATUTORY_MASTER_ENUM_PK PRIMARY KEY (ID)
);
ALTER TABLE STATUTORY_MASTER_ENUM MODIFY COLUMN ID INT(2) AUTO_INCREMENT;
ALTER TABLE STATUTORY_MASTER_ENUM AUTO_INCREMENT=1;

CREATE TABLE DEP_PERCENT_ENUM (
	ID INT(3) NOT NULL,
	ITEM VARCHAR(25) NOT NULL,
	PERCENT_FY INT(3) NOT NULL,
	PERCENT_HY INT(3) NOT NULL,
	CONSTRAINT DEP_PERCENT_ENUM_PK PRIMARY KEY (ID)
);

