
/*CREATE OR REPLACE VIEW ACTIVE_AGENCIES_VIEW AS
   SELECT a.AGENCY_CODE, a.EMAIL_ID, a.CREATED_DATE, a.MODIFIED_DATE,a.IS_FTL,
          b.AGENCY_NAME, b.AGENCY_MOBILE,b.PINNUMBER, b.OFFICE_LANDLINE, b.ADDRESS,
          b.AGENCY_ST_OR_UT, b.AGENCY_OC, b.PAN_NO, b.TIN_NO, b.GSTIN_NO, b.REG_NO,
          b.CONTACT_PERSON, b.EFFECTIVE_DATE, b.DAYEND_DATE, b.LAST_TRXNDATE,
          b.PPSHIP, b.SI_SNO, b.CS_SNO , b.IMAGE_STATUS, b.FTL_FY  FROM AGENCYS a, AGENCY_DETAILS b 
          WHERE a.STATUS = 1 AND a.AGENCY_CODE = b.CREATED_BY;*/


          

CREATE OR REPLACE VIEW ACTIVE_AGENCIES_VIEW AS
   SELECT a.AGENCY_CODE, a.EMAIL_ID, a.CREATED_DATE, a.MODIFIED_DATE,a.IS_FTL,
          b.AGENCY_NAME, b.AGENCY_MOBILE,b.PINNUMBER, b.OFFICE_LANDLINE, b.ADDRESS,
          b.AGENCY_ST_OR_UT, b.AGENCY_OC, b.PAN_NO, b.TIN_NO, b.GSTIN_NO, b.REG_NO,
          b.CONTACT_PERSON, b.EFFECTIVE_DATE, b.DAYEND_DATE, b.LAST_TRXNDATE,
          b.PPSHIP, b.SI_SNO, b.CS_SNO , b.IMAGE_STATUS,b.XL_UPLOAD_STATUS,b.OFFER_PRICE_ACCEPTABLE
          FROM AGENCYS a, AGENCY_DETAILS b
          WHERE a.STATUS = 1 AND a.AGENCY_CODE = b.CREATED_BY;
          
SELECT * FROM ACTIVE_AGENCIES_VIEW;

-- ALTER VIEW VIEW_NAME AS SELECT COL_NAMES FROM TABLE_NAME;
