CREATE TABLE AGENCYS
(
 AGENCY_CODE BIGINT(10) NOT NULL,
 EMAIL_ID VARCHAR(50) NOT NULL,
 PWD VARCHAR(50) NOT NULL,
 STATUS INT(1) NOT NULL,
 IS_FTL INT(1) NOT NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT AGENCYS_PK PRIMARY KEY (AGENCY_CODE),
 CONSTRAINT AGENCYS_EMAILID_UNIQUE UNIQUE (EMAIL_ID)
);


CREATE TABLE AGENCY_DETAILS 
(
 AGENCY_NAME VARCHAR(100) NOT NULL,
 AGENCY_MOBILE VARCHAR(10) NOT NULL,
 OFFICE_LANDLINE VARCHAR(15) NULL,
 ADDRESS VARCHAR(250) NULL,
 AGENCY_ST_OR_UT INT(4) NOT NULL,
 AGENCY_OC INT(1) NOT NULL,
 PPSHIP INT(1) NOT NULL,
 PAN_NO VARCHAR(15) NULL,
 TIN_NO VARCHAR(11) NULL,
 GSTIN_NO VARCHAR(25) NOT NULL,
 REG_NO VARCHAR(20) NULL,
 CONTACT_PERSON VARCHAR(50) NULL,
-- FTL_DATE BIGINT NULL,
 EFFECTIVE_DATE BIGINT NULL,
 DAYEND_DATE  	BIGINT NULL,
 LAST_TRXNDATE  BIGINT NULL,
 PINNUMBER VARCHAR(6) NULL,
 SI_SNO INT(5) NULL,
 CS_SNO INT(5) NULL,
 FTL_FY INT(5) NULL,
 XL_UPLOAD_STATUS INT(1) NOT NULL,
 OFFER_PRICE_ACCEPTABLE INT(1) NOT NULL, 
 CREATED_BY    	BIGINT(10) NOT NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT AGENCY_DETAILS_PK PRIMARY KEY (CREATED_BY),
 CONSTRAINT AGENCY_DETAILS_STORUT_FK FOREIGN KEY (AGENCY_ST_OR_UT) REFERENCES STATES_AND_UT_ENUM(ID)
);
ALTER TABLE AGENCY_DETAILS ADD CONSTRAINT AGENCY_DETAILS_UNIQUE UNIQUE (GSTIN_NO);
ALTER TABLE AGENCY_DETAILS ADD XL_UPLOAD_STATUS INT(1) NOT NULL DEFAULT 0 AFTER FTL_FY;

/*
ALTER TABLE AGENCY_DETAILS ADD COLUMN EFFECTIVE_DATE BIGINT NULL AFTER CONTACT_PERSON; 
ALTER TABLE AGENCY_DETAILS ADD COLUMN LAST_TRXNDATE BIGINT NULL AFTER DAYEND_DATE;
UPDATE AGENCY_DETAILS SET LAST_TRXNDATE = DAYEND_DATE;
alter table AGENCY_DETAILS add column PINNUMBER VARCHAR(6) NULL;

ALTER TABLE AGENCY_DETAILS ADD COLUMN SI_SNO INT(5) NULL AFTER LAST_TRXNDATE; 
ALTER TABLE AGENCY_DETAILS ADD COLUMN CS_SNO INT(5) NULL AFTER SI_SNO;
UPDATE AGENCY_DETAILS SET SI_SNO = 0;
UPDATE AGENCY_DETAILS SET CS_SNO = 0;
ALTER TABLE AGENCY_DETAILS ADD COLUMN FTL_FY INT(5) NULL AFTER CS_SNO;
ALTER TABLE AGENCY_DETAILS ADD IMAGE_STATUS INT NOT NULL DEFAULT 0;
*/

ALTER TABLE AGENCY_DETAILS ADD COLUMN OFFER_PRICE_ACCEPTABLE INT(1) NOT NULL DEFAULT 0 AFTER XL_UPLOAD_STATUS; 
--	offer price will be considered only if dealer wants us to. 
--	(i.e, if offerPrice_acceptable is set to: 
--		1 - then user asked us to consider offerprice
--		0 - default value and offer price is not considered.
--	)


CREATE TABLE ACCOUNT_ACTIVATION (
	AGENCY_CODE BIGINT(10) NOT NULL,
	REQUEST_TYPE INT(1) NOT NULL,
	ACTIVATION_CODE  VARCHAR(50) NOT NULL,
	CREATED_DATE BIGINT NULL,

	CONSTRAINT ACCOUNT_ACTIVATION_PK PRIMARY KEY (AGENCY_CODE,REQUEST_TYPE)
);


CREATE TABLE AGENCY_SERIAL_NOS (
 SI_SNO INT(5) NULL,
 CS_SNO INT(5) NULL,
 PR_SNO INT(5) NULL,
 SR_SNO INT(5) NULL,
 QT_SNO INT(5) NULL,
 DC_SNO INT(5) NULL,
 RCPTS_SNO INT(5) NULL,
 PMTS_SNO INT(5) NULL,
 BT_SNO INT(5) NULL,
 CN_SNO INT(5) NULL,
 DN_SNO INT(5) NULL,
 FY INT(5) NULL,
 CREATED_BY BIGINT(10) NOT NULL,
 CONSTRAINT AGENCY_SERIAL_NO_PK PRIMARY KEY (CREATED_BY)
);

CREATE TABLE STATUTORY_DATA (
	ID BIGINT(10) NOT NULL,
	ITEM_TYPE INT(2) NOT NULL,
	ITEM_REF_NO VARCHAR(25) NOT NULL,
	VALID_UPTO DATETIME NOT NULL,
	REMIND_BEFORE INT(2) NOT NULL,
	REMARKS VARCHAR(50) NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT STATUTORY_DATA_PK PRIMARY KEY (ID),
	CONSTRAINT STATUTORY_DATA_FK FOREIGN KEY (ITEM_TYPE) REFERENCES STATUTORY_MASTER_ENUM(ID)
);
ALTER TABLE STATUTORY_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE STATUTORY_DATA AUTO_INCREMENT=1000001;

CREATE TABLE PRODUCT_CATEGORY_DATA (
	ID INT(4) NOT NULL,
	CAT_CODE VARCHAR(5) NOT NULL,
	CAT_NAME VARCHAR(25) NOT NULL,
	CAT_DESC VARCHAR(60) NOT NULL,
	CAT_TYPE INT(1) NOT NULL,
	DELETED       	INT(1) NOT NULL,
	CONSTRAINT PRODUCT_CATEGORY_DATA_PK PRIMARY KEY (ID)
);

CREATE TABLE STAFF_DATA (
	ID BIGINT(10) NOT NULL,
	EMP_CODE VARCHAR(10) NOT NULL,
	EMP_NAME VARCHAR(50) NOT NULL,
	DOB DATETIME NULL,
	DESIGNATION VARCHAR(50) NOT NULL,
	ROLE INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT STAFF_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE STAFF_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE STAFF_DATA AUTO_INCREMENT=1000001;

/*
CREATE TABLE EXPENDITURE_DATA (
	ID BIGINT(10) NOT NULL,
	ITEM_NAME VARCHAR(10) NOT NULL,
	SH INT(3) NOT NULL,
	MH INT(2) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT EXPENDITURE_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE EXPENDITURE_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE EXPENDITURE_DATA AUTO_INCREMENT=1000001;
*/

CREATE TABLE CREDIT_LIMITS_DATA (
	ID BIGINT(10) NOT NULL,
	CUST_ID BIGINT(10) NOT NULL,
	CREDIT_LIMIT VARCHAR(13) NOT NULL,
	CREDIT_DAYS INT(3) NOT NULL,
	CC_TYPE INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT CREDIT_LIMITS_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE CREDIT_LIMITS_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE CREDIT_LIMITS_DATA AUTO_INCREMENT=1000001;

/*ALTER TABLE CREDIT_LIMITS_DATA MODIFY COLUMN PROD_CODE INT(4) NOT NULL;
ALTER TABLE CREDIT_LIMITS_DATA ADD COLUMN PROD_CODE BIGINT(10) NOT NULL AFTER CUST_ID;  */

/*NEW DISCCOUNT 25/04/2018*/


ALTER TABLE CREDIT_LIMITS_DATA
ADD DISC_19KG_NDNE VARCHAR(8) NOT NULL,
ADD DISC_19KG_CUTTING_GAS VARCHAR(8) NOT NULL,
ADD DISC_35KG_NDNE VARCHAR(8) NOT NULL,
ADD DISC_47_5KG_NDNE VARCHAR(8) NOT NULL,
ADD DISC_450KG_SUMO VARCHAR(8) NOT NULL;


/*----------------------------------------------------*/


CREATE TABLE FLEET_DATA (
	ID BIGINT(10) NOT NULL,
	VEHICLE_NO VARCHAR(10) NOT NULL,
	VEHICLE_MAKE VARCHAR(25) NOT NULL,
	VEHICLE_TYPE INT(1) NOT NULL,
	VEHICLE_USUAGE INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT FLEET_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE FLEET_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE FLEET_DATA AUTO_INCREMENT=1000001;

/*
CREATE TABLE BANK_DATA (
	ID BIGINT(10) NOT NULL,
	BANK_CODE VARCHAR(20) NULL,
	BANK_NAME VARCHAR(25) NOT NULL,
	BANK_ACC_NO VARCHAR(20) NOT NULL,
	BANK_BRANCH VARCHAR(50) NULL,
	BANK_IFSC_CODE VARCHAR(15) NULL,
	ACC_OB DECIMAL(13,2) NOT NULL,
	ACC_CB DECIMAL(13,2) NOT NULL,
	BANK_ADDR VARCHAR(250) NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT BANK_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE BANK_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE BANK_DATA AUTO_INCREMENT=1000001;
*/
CREATE TABLE BANK_DATA (
	ID BIGINT(10) NOT NULL,
	BANK_CODE VARCHAR(20) NULL,
	BANK_NAME VARCHAR(25) NOT NULL,
	BANK_ACC_NO VARCHAR(20) NOT NULL,
	BANK_BRANCH VARCHAR(50) NULL,
	BANK_IFSC_CODE VARCHAR(15) NULL,
	ACC_OB DECIMAL(13,2) NOT NULL,
	ACC_CB DECIMAL(13,2) NOT NULL,
	BANK_ADDR VARCHAR(250) NULL,
	OD_AND_LOAN_ACCEPTABLE_BAL VARCHAR(13) NOT NULL DEFAULT "NA",
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT BANK_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE BANK_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE BANK_DATA AUTO_INCREMENT=1000001;
-- ALTER TABLE BANK_DATA ADD COLUMN OD_AND_LOAN_ACCEPTABLE_BAL VARCHAR(13) NOT NULL DEFAULT "NA" AFTER BANK_ADDR;

CREATE TABLE CVO_DATA (
	ID BIGINT(10) NOT NULL,
	CVO_NAME VARCHAR(50) NOT NULL,
	CVO_ADDRESS VARCHAR(100) NOT NULL,
	CVO_CONTACT VARCHAR(15) NOT NULL,
	CVO_CAT INT(1) NOT NULL,
	IS_GST_REG INT(1) NOT NULL,
	CVO_TIN VARCHAR(20) NULL,
	CVO_EMAIL VARCHAR(50) NULL,
	CVO_PAN VARCHAR(15) NULL,
	OBAL VARCHAR(13) NOT NULL,
	CBAL VARCHAR(13) NOT NULL,
	EBAL VARCHAR(13) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT CVO_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE CVO_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE CVO_DATA AUTO_INCREMENT=1000001;

CREATE TABLE EQUIPMENT_DATA (
	ID BIGINT(10) NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	UNITS INT(1) NOT NULL,
	VATP VARCHAR(5) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	CSTEH_NO VARCHAR(15) NOT NULL,
	SECURITY_DEPOSIT VARCHAR(8) NOT NULL,
	OS_FULLS INT(4) NOT NULL,
	OS_EMPTYS INT(4) NOT NULL,
	CS_FULLS INT(4) NOT NULL,
	CS_EMPTYS INT(4) NOT NULL,
	EFFECTIVE_DATE 	BIGINT NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT EQUIPMENT_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE EQUIPMENT_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE EQUIPMENT_DATA AUTO_INCREMENT=1000001;

CREATE TABLE ARB_DATA (
	ID BIGINT(10) NOT NULL,
	PROD_CODE VARCHAR(4) NOT NULL,
	PROD_BRAND VARCHAR(25) NOT NULL,
	PROD_NAME VARCHAR(25) NOT NULL,
	UNITS INT(1) NOT NULL,
	VATP VARCHAR(5) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	CSTEH_NO VARCHAR(15) NOT NULL,
	PROD_MRP VARCHAR(8) NOT NULL,
	PROD_OFFER_PRICE VARCHAR(8) NOT NULL,
	OPENING_STOCK INT(4) NOT NULL,
	CURRENT_STOCK INT(4) NOT NULL,
	EFFECTIVE_DATE 	BIGINT NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT ARB_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE ARB_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE ARB_DATA AUTO_INCREMENT=1000001;

/*
CREATE TABLE SERVICES_DATA (
	ID BIGINT(10) NOT NULL,
	PROD_CODE VARCHAR(4) NOT NULL,
	PROD_CHARGES VARCHAR(8) NOT NULL,
	GST_AMT VARCHAR(8) NOT NULL,
	SAC_CODE VARCHAR(10) NOT NULL,
	EFFECTIVE_DATE 	BIGINT NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT SERVICES_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE SERVICES_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE SERVICES_DATA AUTO_INCREMENT=1000001;

ALTER TABLE SERVICES_DATA ADD GSTP_APPLICABLE_AMT VARCHAR(8) NOT NULL;
ALTER TABLE SERVICES_DATA ADD GST_PERCENT_APPLICABLE VARCHAR(8) NOT NULL;
*/



/*------------------------ SERVICES DATA START 14052019 ---------------------------------*/


CREATE TABLE SERVICES_DATA (
	ID BIGINT(10) NOT NULL,
	PROD_CODE VARCHAR(4) NOT NULL,
	PROD_CHARGES VARCHAR(8) NOT NULL,
	GST_AMT VARCHAR(8) NOT NULL,
	SAC_CODE VARCHAR(10) NOT NULL,
	EFFECTIVE_DATE 	BIGINT NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT SERVICES_DATA_PK PRIMARY KEY (PROD_CODE)
);
ALTER TABLE SERVICES_DATA ADD UNIQUE (ID);
ALTER TABLE SERVICES_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE SERVICES_DATA AUTO_INCREMENT=1000001;

CREATE TABLE SERVICES_GST
(
 ID BIGINT(10) NOT NULL,
 SERVICE_PRODUCT_ID VARCHAR(4) NOT NULL,
 GSTP_APPLICABLE_AMT VARCHAR(8) NOT NULL,
 GST_PERCENT_APPLICABLE VARCHAR(8) NOT NULL,
 CREATED_BY    	BIGINT(10) NOT NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT SERVICES_GST_PK PRIMARY KEY(ID),
 CONSTRAINT SERVICES_GST_SERVICES_PROCODE_FK FOREIGN KEY (SERVICE_PRODUCT_ID) REFERENCES SERVICES_DATA(PROD_CODE)
);

ALTER TABLE SERVICES_GST MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE SERVICES_GST AUTO_INCREMENT=10001;

/*------------------------------- SERVICES DATA END 14052019 -----------------------------*/



CREATE TABLE AREA_CODE_DATA (
	ID BIGINT(10) NOT NULL,
	AREA_CODE VARCHAR(8) NOT NULL,
	AREA_NAME VARCHAR(50) NOT NULL,
	ONE_WAY_DIST INT(3) NOT NULL,
	TRANSPORT_CHARGES VARCHAR(8) NOT NULL,
	EFFECTIVE_DATE  BIGINT NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(11) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT AREA_CODE_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE AREA_CODE_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE AREA_CODE_DATA AUTO_INCREMENT=1000001;

CREATE TABLE REFILL_PRICES_DATA (
	ID BIGINT(10) NOT NULL,
	PROD_CODE VARCHAR(4) NOT NULL,
	BASE_PRICE VARCHAR(8) NOT NULL,
	SGST_PRICE VARCHAR(8) NOT NULL,
	CGST_PRICE VARCHAR(8) NOT NULL,
	RSP VARCHAR(8) NOT NULL,
	OFFER_PRICE VARCHAR(8) NOT NULL,
	OP_BASE_PRICE VARCHAR(8) NOT NULL,
	MONTHA INT(2) NOT NULL,
	YEARA INT(4) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT REFILL_PRICES_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE REFILL_PRICES_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE REFILL_PRICES_DATA AUTO_INCREMENT=1000001;

-- ALTER TABLE REFILL_PRICES_DATA ADD COLUMN OP_BASE_PRICE VARCHAR(8) NOT NULL AFTER OFFER_PRICE;

CREATE TABLE ARB_PRICES_DATA (
	ID BIGINT(10) NOT NULL,
	ARB_CODE BIGINT(10) NOT NULL,
	BASE_PRICE VARCHAR(8) NOT NULL,
	SGST_PRICE VARCHAR(8) NOT NULL,
	CGST_PRICE VARCHAR(8) NOT NULL,
	RSP VARCHAR(8) NOT NULL,
	OFFER_PRICE VARCHAR(8) NOT NULL,
	OP_BASE_PRICE VARCHAR(8) NOT NULL,
	MONTHA INT(2) NOT NULL,
	YEARA INT(4) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT ARB_PRICES_MASTER_PK PRIMARY KEY (ID)
);
ALTER TABLE ARB_PRICES_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE ARB_PRICES_DATA AUTO_INCREMENT=1000001;

-- ALTER TABLE ARB_PRICES_DATA ADD COLUMN OP_BASE_PRICE VARCHAR(8) NOT NULL AFTER OFFER_PRICE;

CREATE TABLE CYLD_PURCHASE_INVS (
	ID BIGINT(10) NOT NULL,
	OMC_ID BIGINT(10) NOT NULL,
	INV_REF_NO VARCHAR(25) NOT NULL,
	INV_DATE BIGINT NOT NULL,
	STK_RECVD_DATE BIGINT NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	EMR_OR_DELV INT(1) NOT NULL,
	UNIT_PRICE VARCHAR(8) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	CS_FULLS INT(4) NOT NULL,
	CS_EMPTYS INT(4) NOT NULL,
	DS_FULLS INT(4) NOT NULL,
	DS_EMPTYS INT(4) NOT NULL,
/*	DSS_FULLS INT(4) NOT NULL,
	DSS_EMPTYS INT(4) NOT NULL, */
	GSTP VARCHAR(5) NOT NULL,
	OTHER_CHARGES VARCHAR(8) NOT NULL,
	BASIC_AMOUNT VARCHAR(10) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	C_AMOUNT VARCHAR(13) NOT NULL,
	VBAL_AMOUNT VARCHAR(13) NULL,
	CVO_BY    	BIGINT(10) NULL,
	PAYMENT_STATUS INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT CYLD_PURCHASE_INVS_PK PRIMARY KEY (ID)
);
ALTER TABLE CYLD_PURCHASE_INVS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE CYLD_PURCHASE_INVS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE CYLD_PURCHASE_INVS DROP COLUMN DSS_EMPTYS;
-- ------DROPED------ ALTER TABLE CYLD_PURCHASE_INVS DROP COLUMN DSS_FULLS;

/*
ALTER TABLE CYLD_PURCHASE_INVS ADD COLUMN DSS_FULLS INT(4) NOT NULL DEFAULT 0 AFTER DS_EMPTYS;
ALTER TABLE CYLD_PURCHASE_INVS ADD COLUMN DSS_EMPTYS INT(4) NOT NULL DEFAULT 0 AFTER DSS_FULLS;
UPDATE CYLD_PURCHASE_INVS SET DSS_FULLS=CS_FULLS,DSS_EMPTYS= CS_EMPTYS;
*/

CREATE TABLE ARB_PURCHASE_INVS (
	ID BIGINT(10) NOT NULL,
	INV_REF_NO VARCHAR(25) NOT NULL,
	INV_DATE BIGINT NOT NULL,
	STK_RECVD_DATE BIGINT NOT NULL,
	ARB_CODE BIGINT(10) NOT NULL,
	VENDOR_ID BIGINT NOT NULL,
	REVERSE_CHARGE INT(1) NOT NULL,
	UNIT_PRICE VARCHAR(8) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	OTHER_CHARGES VARCHAR(8) NOT NULL,
	BASIC_AMOUNT VARCHAR(10) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	C_AMOUNT VARCHAR(13) NOT NULL,
	VBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
--	VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
	C_STOCK INT(4) NOT NULL,
	D_STOCK INT(4) NOT NULL,
--	DSS_STOCK INT(4) NOT NULL,	
	CVO_BY    	BIGINT(10) NULL,
	PAYMENT_STATUS INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT ARB_PURCHASE_INVS_PK PRIMARY KEY (ID)
);
ALTER TABLE ARB_PURCHASE_INVS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE ARB_PURCHASE_INVS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE ARB_PURCHASE_INVS DROP COLUMN VBAL_AMOUNT_AFTER_DS;
-- ------DROPED------ ALTER TABLE ARB_PURCHASE_INVS DROP COLUMN DSS_STOCK;

--ALTER TABLE ARB_PURCHASE_INVS ADD COLUMN VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
--UPDATE ARB_PURCHASE_INVS SET VBAL_AMOUNT_AFTER_DS = VBAL_AMOUNT;
--ALTER TABLE ARB_PURCHASE_INVS ADD COLUMN DSS_STOCK INT(4) NOT NULL DEFAULT 0 AFTER D_STOCK;
--UPDATE ARB_PURCHASE_INVS SET DSS_STOCK = C_STOCK;

CREATE TABLE OTHER_PURCHASE_INVS (
	ID BIGINT(10) NOT NULL,
	INV_REF_NO VARCHAR(25) NOT NULL,
	INV_DATE BIGINT NOT NULL,
	VENDOR_ID BIGINT NOT NULL,
	PAYMENT_STATUS INT(1) NOT NULL,
	REVERSE_CHARGE INT(1) NOT NULL,
	PNAME VARCHAR(20) NOT NULL,
	TAXABLE INT(1) NOT NULL,
	HSN_CODE VARCHAR(10) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	MH INT(3) NOT NULL,
	CH INT(3) NOT NULL,
	AH INT(3) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	UOM INT(3) NOT NULL,
	UNIT_RATE VARCHAR(10) NOT NULL,
	BASIC_AMOUNT VARCHAR(10) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	P_AMOUNT VARCHAR(13) NOT NULL,
	VBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
--	VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT OTHER_PURCHASE_INVS_PK PRIMARY KEY (ID)
);
ALTER TABLE OTHER_PURCHASE_INVS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE OTHER_PURCHASE_INVS AUTO_INCREMENT=1000001;

ALTER TABLE OTHER_PURCHASE_INVS ADD COLUMN VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
UPDATE OTHER_PURCHASE_INVS SET VBAL_AMOUNT_AFTER_DS=VBAL_AMOUNT;

-- ------DROPED------ ALTER TABLE OTHER_PURCHASE_INVS DROP COLUMN VBAL_AMOUNT_AFTER_DS;

CREATE TABLE QUOTATIONS (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	QTN_DATE BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	CUSTOMER_NAME VARCHAR(30) NOT NULL DEFAULT "NA",
	STAFF_ID BIGINT NOT NULL,
	QTN_AMOUNT VARCHAR(13) NOT NULL,
	FOOT_NOTES VARCHAR(100) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT QUOTATIONS_PK PRIMARY KEY (ID)
);
ALTER TABLE QUOTATIONS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE QUOTATIONS AUTO_INCREMENT=1000001;

ALTER TABLE QUOTATIONS ADD COLUMN FOOT_NOTES VARCHAR(100) NOT NULL DEFAULT "EMPTY" AFTER QTN_AMOUNT;
ALTER TABLE QUOTATIONS ADD COLUMN CUSTOMER_NAME VARCHAR(30) NOT NULL DEFAULT "NA" AFTER CUSTOMER_ID;

CREATE TABLE QUOTATION_DETAILS (
	ID BIGINT(10) NOT NULL,
	QTN_ID BIGINT NOT NULL,
	PROD_CODE BIGINT(10) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	VATP VARCHAR(5) NOT NULL,
	UNIT_RATE VARCHAR(8) NOT NULL,
	DISC_UNIT_RATE VARCHAR(8) NOT NULL,
	BASIC_AMOUNT VARCHAR(10) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	PROD_AMOUNT VARCHAR(10) NOT NULL,
	CONSTRAINT QUOTATION_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT QUOTATION_DETAILS_FK FOREIGN KEY (QTN_ID) REFERENCES QUOTATIONS(ID)
);
ALTER TABLE QUOTATION_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE QUOTATION_DETAILS AUTO_INCREMENT=1000001;

/* ALTER TABLE QUOTATION_DETAILS MODIFY COLUMN BASIC_AMOUNT VARCHAR(10); */
ALTER TABLE QUOTATION_DETAILS DROP COLUMN FOOT_NOTES;


CREATE TABLE DELIVERY_CHALLANS (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	DC_DATE BIGINT NOT NULL,
	DC_REF_DATE BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	FLEET_ID BIGINT NOT NULL,
	DC_AMOUNT VARCHAR(13) NOT NULL,
	INV_NO VARCHAR(25) NOT NULL,
	DELIVERY_MODE VARCHAR(40) NOT NULL,
	DELIVERY_INSTRUCTIONS VARCHAR(100) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT DELIVERY_CHALLANS PRIMARY KEY (ID)
);
ALTER TABLE DELIVERY_CHALLANS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE DELIVERY_CHALLANS AUTO_INCREMENT=1000001;

/*ALTER TABLE DELIVERY_CHALLANS ADD COLUMN DC_REF_DATE BIGINT NOT NULL AFTER DC_DATE; */

CREATE TABLE DELIVERY_CHALLAN_DETAILS (
	ID BIGINT(10) NOT NULL,
	DC_ID BIGINT NOT NULL,
	PROD_CODE VARCHAR(10) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	UNIT_RATE VARCHAR(8) NOT NULL,
	BASIC_AMOUNT VARCHAR(10) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	PROD_AMOUNT VARCHAR(10) NOT NULL,
	CONSTRAINT DELIVERY_CHALLAN_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT DELIVERY_CHALLAN_DETAILS_FK FOREIGN KEY (DC_ID) REFERENCES DELIVERY_CHALLANS(ID)
);
ALTER TABLE DELIVERY_CHALLAN_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE DELIVERY_CHALLAN_DETAILS AUTO_INCREMENT=1000001;

-- ALTER TABLE DELIVERY_CHALLAN_DETAILS MODIFY COLUMN PROD_CODE VARCHAR(10) NOT NULL;

CREATE TABLE AGENCY_BOM(
	ID BIGINT(10) NOT NULL,
	BOM_NAME VARCHAR(50) NOT NULL,
	BOM_TYPE INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT AGENCY_BOM_PK PRIMARY KEY (ID)
);
ALTER TABLE AGENCY_BOM MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE AGENCY_BOM AUTO_INCREMENT=1000001;

CREATE TABLE AGENCY_BOM_ITEMS(
	ID BIGINT(10) NOT NULL,
	BOM_ID BIGINT NOT NULL,
	PROD_CODE BIGINT NOT NULL,
	QTY INT(1) NOT NULL,
	DEPOSIT_REQ VARCHAR(3) NOT NULL,
	CONSTRAINT AGENCY_BOM_ITEMS_PK PRIMARY KEY (ID),
	CONSTRAINT AGENCY_BOM_ITEMS_FK FOREIGN KEY (BOM_ID) REFERENCES AGENCY_BOM(ID)
);
ALTER TABLE AGENCY_BOM_ITEMS MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE AGENCY_BOM_ITEMS AUTO_INCREMENT=1000001;

CREATE TABLE DOM_SALES_INVOICES (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	SI_DATE BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	PAYMENT_TERMS INT(1) NOT NULL,
	PAYMENT_STATUS INT(1) NOT NULL,
	CASH_AMOUNT VARCHAR(13) NOT NULL,
	SI_AMOUNT VARCHAR(13) NOT NULL,
	CBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
	CBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
	DISCOUNT VARCHAR(8) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT DOM_SALES_INVOICES_PK PRIMARY KEY (ID)
);
ALTER TABLE DOM_SALES_INVOICES MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE DOM_SALES_INVOICES AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE DOM_SALES_INVOICES DROP COLUMN CBAL_AMOUNT_AFTER_DS;

/* ALTER TABLE DOM_SALES_INVOICES ADD COLUMN BAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL AFTER DBAL_AMOUNT;
UPDATE DOM_SALES_INVOICES SET BAL_AMOUNT_AFTER_DS = 0;
ALTER TABLE DOM_SALES_INVOICES CHANGE COLUMN BAL_AMOUNT_AFTER_DS BAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0; 
ALTER TABLE DOM_SALES_INVOICES CHANGE COLUMN BAL_AMOUNT_AFTER_DS CBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0;

ALTER TABLE DOM_SALES_INVOICES ADD COLUMN DISCOUNT VARCHAR(8) NOT NULL AFTER CBAL_AMOUNT_AFTER_DS;
*/


CREATE TABLE DOM_SALES_INVOICES_DETAILS (
	ID BIGINT NOT NULL,
	DSI_ID BIGINT NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	UNIT_RATE VARCHAR(8) NOT NULL,
	DISC_UNIT_RATE VARCHAR(8) NOT NULL,
	PRE_CYLS INT(3) NOT NULL,
	PSV_CYLS INT(3) NOT NULL,
	CS_FULLS INT(4) NOT NULL,
	CS_EMPTYS INT(4) NOT NULL,
	DS_FULLS INT(4) NOT NULL,
	DS_EMPTYS INT(4) NOT NULL,
--	DSS_FULLS INT(4) NOT NULL,
--	DSS_EMPTYS INT(4) NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	AC_ID BIGINT NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	SALE_AMOUNT VARCHAR(10) NOT NULL,
	BANK_ID BIGINT NOT NULL,
	AMOUNT_RCVD_ONLINE VARCHAR(10) NOT NULL,
	CONSTRAINT DOM_SALES_INVOICES_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT DOM_SALES_INVOICES_DETAILS_FK FOREIGN KEY (DSI_ID) REFERENCES DOM_SALES_INVOICES(ID)
);
ALTER TABLE DOM_SALES_INVOICES_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE DOM_SALES_INVOICES_DETAILS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE DOM_SALES_INVOICES_DETAILS DROP COLUMN DSS_FULLS;
-- ------DROPED------ ALTER TABLE DOM_SALES_INVOICES_DETAILS DROP COLUMN DSS_EMPTYS;

--  ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN OP_BASIC_PRICE VARCHAR(10) NOT NULL AFTER CGST_AMOUNT;
--  ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN OP_TAXABLE_AMT VARCHAR(10) NOT NULL AFTER OP_BASIC_PRICE;
--	ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN OP_TOTAL_AMT VARCHAR(10) NOT NULL AFTER OP_TAXABLE_AMT;
--	ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN OP_IGST_AMT VARCHAR(10) NOT NULL AFTER OP_TOTAL_AMT;
--	ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN OP_SGST_AMT VARCHAR(10) NOT NULL AFTER OP_IGST_AMT;
--	ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN OP_CGST_AMT VARCHAR(10) NOT NULL AFTER OP_SGST_AMT;

/*
ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN DSS_FULLS INT(4) NOT NULL AFTER DS_EMPTYS;
ALTER TABLE DOM_SALES_INVOICES_DETAILS ADD COLUMN DSS_EMPTYS INT(4) NOT NULL AFTER DSS_FULLS;
UPDATE DOM_SALES_INVOICES_DETAILS SET DSS_FULLS = CS_FULLS, DSS_EMPTYS = CS_EMPTYS;
*/

CREATE TABLE COM_SALES_INVOICES (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	SI_DATE BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	CASH_AMOUNT VARCHAR(13) NOT NULL,
	SI_AMOUNT VARCHAR(13) NOT NULL,
	CBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
--	CBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
	PAYMENT_TERMS INT(1) NOT NULL,
	PAYMENT_STATUS INT(1) NOT NULL,
	DISCOUNT VARCHAR(8) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT COM_SALES_INVOICES_PK PRIMARY KEY (ID)
);
ALTER TABLE COM_SALES_INVOICES MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE COM_SALES_INVOICES AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE COM_SALES_INVOICES DROP COLUMN CBAL_AMOUNT_AFTER_DS;

--ALTER TABLE COM_SALES_INVOICES ADD COLUMN CBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
--UPDATE COM_SALES_INVOICES SET CBAL_AMOUNT_AFTER_DS = CBAL_AMOUNT;
--ALTER TABLE COM_SALES_INVOICES ADD COLUMN DISCOUNT VARCHAR(8) NOT NULL AFTER PAYMENT_STATUS;

CREATE TABLE COM_SALES_INVOICES_DETAILS (
	ID BIGINT NOT NULL,
	CSI_ID BIGINT NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	UNIT_RATE VARCHAR(8) NOT NULL,
	DISC_UNIT_RATE VARCHAR(8) NOT NULL,
	PRE_CYLS INT(3) NOT NULL,
	PSV_CYLS INT(3) NOT NULL,
	CS_FULLS INT(4) NOT NULL,
	CS_EMPTYS INT(4) NOT NULL,
	DS_FULLS INT(4) NOT NULL,
	DS_EMPTYS INT(4) NOT NULL,
--	DSS_FULLS INT(4) NOT NULL,
--	DSS_EMPTYS INT(4) NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	AC_ID BIGINT NOT NULL,
	BANK_ID BIGINT NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	SALE_AMOUNT VARCHAR(10) NOT NULL,
	CONSTRAINT COM_SALES_INVOICES_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT COM_SALES_INVOICES_DETAILS_FK FOREIGN KEY (CSI_ID) REFERENCES COM_SALES_INVOICES(ID)
);
ALTER TABLE COM_SALES_INVOICES_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE COM_SALES_INVOICES_DETAILS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE COM_SALES_INVOICES_DETAILS DROP COLUMN DSS_FULLS;
-- ------DROPED------ ALTER TABLE COM_SALES_INVOICES_DETAILS DROP COLUMN DSS_EMPTYS;

--  ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN OP_BASIC_PRICE VARCHAR(10) NOT NULL AFTER CGST_AMOUNT;
--  ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN OP_TAXABLE_AMT VARCHAR(10) NOT NULL AFTER OP_BASIC_PRICE;
--	ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN OP_TOTAL_AMT VARCHAR(10) NOT NULL AFTER OP_TAXABLE_AMT;
--	ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN OP_IGST_AMT VARCHAR(10) NOT NULL AFTER OP_TOTAL_AMT;
--	ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN OP_SGST_AMT VARCHAR(10) NOT NULL AFTER OP_IGST_AMT;
--	ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN OP_CGST_AMT VARCHAR(10) NOT NULL AFTER OP_SGST_AMT;

--ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN DSS_FULLS INT(4) NOT NULL DEFAULT 0 AFTER DS_EMPTYS;
--ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN DSS_EMPTYS INT(4) NOT NULL DEFAULT 0 AFTER DSS_FULLS;
--UPDATE COM_SALES_INVOICES_DETAILS SET DSS_FULLS = CS_FULLS, DSS_EMPTYS = CS_EMPTYS;
ALTER TABLE COM_SALES_INVOICES_DETAILS ADD COLUMN BANK_ID BIGINT NOT NULL AFTER AC_ID;

CREATE TABLE ARB_SALES_INVOICES (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	SI_DATE BIGINT NOT NULL,
	CUSTOMER_ID BIGINT NOT NULL,
	SI_AMOUNT VARCHAR(13) NOT NULL,
	CBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
--	CBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
	PAYMENT_TERMS INT(1) NOT NULL,
	PAYMENT_STATUS INT(1) NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	DISCOUNT VARCHAR(8) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT ARB_SALES_INVOICES_PK PRIMARY KEY (ID)
);
ALTER TABLE ARB_SALES_INVOICES MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE ARB_SALES_INVOICES AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE ARB_SALES_INVOICES DROP COLUMN CBAL_AMOUNT_AFTER_DS;

/*
ALTER TABLE ARB_SALES_INVOICES ADD COLUMN CBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL AFTER DBAL_AMOUNT;
UPDATE ARB_SALES_INVOICES SET CBAL_AMOUNT_AFTER_DS = CBAL_AMOUNT;
*/
--ALTER TABLE ARB_SALES_INVOICES ADD COLUMN DISCOUNT VARCHAR(8) NOT NULL AFTER STAFF_ID;

CREATE TABLE ARB_SALES_INVOICES_DETAILS (
	ID BIGINT NOT NULL,
	ARBSI_ID BIGINT NOT NULL,
	PROD_CODE BIGINT NOT NULL,
	QUANTITY INT(5) NOT NULL,
	C_STOCK INT(5) NOT NULL,
	D_STOCK INT(5) NOT NULL,
--	DS_STOCK INT(5) NOT NULL,
	UNIT_RATE VARCHAR(8) NOT NULL,
	DISC_UNIT_RATE VARCHAR(8) NOT NULL,
	BANK_ID BIGINT NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
		
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	
	SALE_AMOUNT VARCHAR(10) NOT NULL,
	CONSTRAINT ARB_SALES_INVOICES_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT ARB_SALES_INVOICES_DETAILS_FK FOREIGN KEY (ARBSI_ID) REFERENCES ARB_SALES_INVOICES(ID)
);
ALTER TABLE ARB_SALES_INVOICES_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE ARB_SALES_INVOICES_DETAILS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE ARB_SALES_INVOICES_DETAILS DROP COLUMN DS_STOCK;

--  ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN OP_BASIC_PRICE VARCHAR(10) NOT NULL AFTER CGST_AMOUNT;
--  ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN OP_TAXABLE_AMT VARCHAR(10) NOT NULL AFTER OP_BASIC_PRICE;
--	ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN OP_TOTAL_AMT VARCHAR(10) NOT NULL AFTER OP_TAXABLE_AMT;
--	ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN OP_IGST_AMT VARCHAR(10) NOT NULL AFTER OP_TOTAL_AMT;
--	ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN OP_SGST_AMT VARCHAR(10) NOT NULL AFTER OP_IGST_AMT;
--	ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN OP_CGST_AMT VARCHAR(10) NOT NULL AFTER OP_SGST_AMT;

/*
ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN DS_STOCK INT(5) NOT NULL AFTER D_STOCK;
UPDATE ARB_SALES_INVOICES_DETAILS SET DS_STOCK = C_STOCK;
*/

ALTER TABLE ARB_SALES_INVOICES_DETAILS ADD COLUMN BANK_ID BIGINT NOT NULL AFTER DISC_UNIT_RATE;


CREATE TABLE RECEIPTS_DATA (
	ID BIGINT NOT NULL,
	SR_NO BIGINT(5) NOT NULL,
	RCP_DATE BIGINT NOT NULL,
	RCVD_FROM BIGINT NOT NULL,
	RCP_AMOUNT VARCHAR(10) NOT NULL,
	CBAL_AMOUNT VARCHAR(10) NOT NULL,
	DBAL_AMOUNT VARCHAR(10) NOT NULL,
--	CBAL_AMOUNT_AFTER_DS VARCHAR(10) NOT NULL,
	PAYMENT_MODE INT(1) NOT NULL,
	INSTR_DETAILS VARCHAR(30) NOT NULL,
	CREDITED_BANK BIGINT NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	NARRATION VARCHAR(200) NOT NULL,
	CLEARANCE_STATUS INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT EQUIPMENT_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE RECEIPTS_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE RECEIPTS_DATA AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE RECEIPTS_DATA DROP COLUMN CBAL_AMOUNT_AFTER_DS;

/*
ALTER TABLE RECEIPTS_DATA ADD COLUMN CBAL_AMOUNT_AFTER_DS VARCHAR(10) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
UPDATE RECEIPTS_DATA SET CBAL_AMOUNT_AFTER_DS = CBAL_AMOUNT;
*/

/*
CREATE TABLE PAYMENTS_DATA (
	ID BIGINT NOT NULL,
	SR_NO BIGINT(5) NOT NULL,
	PYMT_DATE BIGINT NOT NULL,
	PAID_TO BIGINT NOT NULL,
	PYMT_AMOUNT VARCHAR(10) NOT NULL,
	VBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
	PAYMENT_MODE INT(1) NOT NULL,
	CUST_VEN INT(1) NOT NULL,
	INSTR_DETAILS VARCHAR(30) NOT NULL,
	DEBITED_BANK BIGINT NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	NARRATION VARCHAR(200) NOT NULL,
	CLEARANCE_STATUS INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT EQUIPMENT_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE PAYMENTS_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE PAYMENTS_DATA AUTO_INCREMENT=1000001;

*/

CREATE TABLE PAYMENTS_DATA (
	ID BIGINT NOT NULL,
    SR_NO BIGINT(5) NOT NULL,
    PYMT_DATE BIGINT NOT NULL,
    PAID_TO BIGINT NOT NULL,
    TAX_TYPE INT(1) NOT NULL,
    PYMT_AMOUNT VARCHAR(10) NOT NULL,
    BANK_CHARGES VARCHAR(10) NOT NULL,
    VBAL_AMOUNT VARCHAR(13) NOT NULL,
    DBAL_AMOUNT VARCHAR(13) NOT NULL,
--    VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
    PAYMENT_MODE INT(1) NOT NULL,
    CUST_VEN INT(1) NOT NULL,
    INSTR_DETAILS VARCHAR(30) NOT NULL,
    DEBITED_BANK BIGINT NOT NULL,
    STAFF_ID BIGINT NOT NULL,
    NARRATION VARCHAR(200) NOT NULL,
    CLEARANCE_STATUS INT(1) NOT NULL,
    CREATED_BY            BIGINT(10) NULL,
    CREATED_DATE          BIGINT NULL,
    MODIFIED_BY           BIGINT(10) NULL,
    MODIFIED_DATE         BIGINT NULL,
    VERSION               INT(1) NULL,
    DELETED               INT(1) NULL,
    CONSTRAINT EQUIPMENT_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE PAYMENTS_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE PAYMENTS_DATA AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE PAYMENTS_DATA DROP COLUMN VBAL_AMOUNT_AFTER_DS;

/* ALTER TABLE PAYMENTS_DATA ADD COLUMN BANK_CHARGES VARCHAR(10) NOT NULL AFTER PYMT_AMOUNT; */ ------------
----ALTER TABLE PAYMENTS_DATA ADD COLUMN VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
----UPDATE PAYMENTS_DATA SET VBAL_AMOUNT_AFTER_DS = VBAL_AMOUNT;

CREATE TABLE BANK_TRANS_DATA (
	ID BIGINT NOT NULL,
	SR_NO BIGINT(5) NOT NULL,
	REF_ID BIGINT(10) NOT NULL,
	BT_DATE BIGINT NOT NULL,
	BANK_ID BIGINT NOT NULL,
	TRANS_AMOUNT VARCHAR(10) NOT NULL,
	TRANS_CHARGES VARCHAR(10) NOT NULL,
	TRANS_TYPE INT(1) NOT NULL,
	TRANS_MODE INT(1) NOT NULL,
	INSTR_DETAILS VARCHAR(30) NOT NULL,
	ACC_HEAD INT(1) NOT NULL,
	BANK_ACB DECIMAL(10,2) NOT NULL,
	DBANK_ACB DECIMAL(10,2) NOT NULL,
--	DSBANK_ACB DECIMAL(10,2) NOT NULL DEFAULT 0,
	NARRATION VARCHAR(100) NULL,
	BTFLAG 			INT(1) DEFAULT 0,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT EQUIPMENT_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE BANK_TRANS_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE BANK_TRANS_DATA AUTO_INCREMENT=1000001;

/*
ALTER TABLE BANK_TRANS_DATA ADD COLUMN DSBANK_ACB DECIMAL(10,2) NOT NULL AFTER DBANK_ACB;
UPDATE BANK_TRANS_DATA SET DSBANK_ACB = 0;
ALTER TABLE BANK_TRANS_DATA CHANGE COLUMN DSBANK_ACB DSBANK_ACB DECIMAL(10,2) NOT NULL DEFAULT 0;
UPDATE BANK_TRANS_DATA SET DSBANK_ACB = BANK_ACB;
ALTER TABLE BANK_TRANS_DATA ADD COLUMN REF_ID BIGINT(10) NOT NULL AFTER SR_NO;
ALTER TABLE BANK_TRANS_DATA DROP COLUMN DSBANK_ACB;
*/

/*
BTFLAG = 1 : BankTransactions,
BTFLAG = 2 : NCDBC - delete,
BTFLAG = 3 : SaveAgencyPurchases,
BTFLAG = 4 : SaveAgencyDSInvoices,delete
BTFLAG = 5 : SaveAgencyNCDBCInvoices,
BTFLAG = 6 : SaveAgencyRCData,
BTFLAG = 7 : SaveAgencyTVData,
BTFLAG = 8 : SaveAgencyReceiptsData,
BTFLAG = 9 : SaveAgencyPaymentsData,
BTFLAG = 10 : SaveAgencyCreditNotes,
BTFLAG = 11 : SaveAgencyDebitNotes,
BTFLAG = 12 : SaveAgencyAssetsData,
BTFLAG = 13 : saveAgencyPartnersTranxsData.
*/

CREATE TABLE CREDIT_NOTES (
	ID BIGINT NOT NULL,
	SID VARCHAR(30) NOT NULL,
	NOTE_DATE BIGINT NOT NULL,
	REF_NO VARCHAR(25) NOT NULL,
	REF_DATE BIGINT NOT NULL,
	CREDIT_NOTE_TYPE INT(1) NOT NULL,
	CVO_ID BIGINT NOT NULL,
	PROD_CODE BIGINT(10) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	TAXABLE_AMOUNT VARCHAR(13) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,	
	CREDIT_AMOUNT VARCHAR(10) NOT NULL,
	CBAL_AMOUNT VARCHAR(10) NOT NULL,
	DBAL_AMOUNT VARCHAR(10) NOT NULL,
--	CBAL_AMOUNT_AFTER_DS VARCHAR(10) NOT NULL,
	BANK_ID BIGINT NOT NULL,
	NREASONS INT(2) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT CREDIT_NOTES_PK PRIMARY KEY (ID)
);
ALTER TABLE CREDIT_NOTES MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE CREDIT_NOTES AUTO_INCREMENT=1000001;

ALTER TABLE CREDIT_NOTES MODIFY COLUMN CBAL_AMOUNT VARCHAR(13) NOT NULL;

-- ------DROPED------ ALTER TABLE CREDIT_NOTES DROP COLUMN CBAL_AMOUNT_AFTER_DS;

-- ALTER TABLE CREDIT_NOTES ADD COLUMN REF_DATE BIGINT NOT NULL AFTER REF_NO;


-- ---ALTER TABLE CREDIT_NOTES ADD COLUMN CBAL_AMOUNT_AFTER_DS VARCHAR(10) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
-- ---UPDATE CREDIT_NOTES SET CBAL_AMOUNT_AFTER_DS = CBAL_AMOUNT;


CREATE TABLE DEBIT_NOTES (
	ID BIGINT NOT NULL,
	SID VARCHAR(30) NOT NULL,
	NOTE_DATE BIGINT NOT NULL,
	REF_NO VARCHAR(25) NOT NULL,
	REF_DATE BIGINT NOT NULL,
	DEBIT_NOTE_TYPE INT(1) NOT NULL,
	CVO_ID BIGINT NOT NULL,
	PROD_CODE BIGINT(10) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	TAXABLE_AMOUNT VARCHAR(13) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,	
	DEBIT_AMOUNT VARCHAR(10) NOT NULL,
	CBAL_AMOUNT VARCHAR(10) NOT NULL,
	DBAL_AMOUNT VARCHAR(10) NOT NULL,
--	CBAL_AMOUNT_AFTER_DS VARCHAR(10) NOT NULL,
	BANK_ID BIGINT NOT NULL,
	NREASONS INT(2) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT DEBIT_NOTES_PK PRIMARY KEY (ID)
);
ALTER TABLE DEBIT_NOTES MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE DEBIT_NOTES AUTO_INCREMENT=1000001;

ALTER TABLE DEBIT_NOTES MODIFY COLUMN CBAL_AMOUNT VARCHAR(13) NOT NULL;

-- ------DROPED------ ALTER TABLE DEBIT_NOTES DROP COLUMN CBAL_AMOUNT_AFTER_DS;

-- ALTER TABLE DEBIT_NOTES ADD COLUMN REF_DATE BIGINT NOT NULL AFTER REF_NO;

-----ALTER TABLE DEBIT_NOTES ADD COLUMN CBAL_AMOUNT_AFTER_DS VARCHAR(10) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
-----UPDATE DEBIT_NOTES SET CBAL_AMOUNT_AFTER_DS = CBAL_AMOUNT;


CREATE TABLE ASSETS_DATA (
	ID BIGINT NOT NULL,
	ASSET_TDATE BIGINT NOT NULL,
	ASSET_TTYPE INT(1) NOT NULL,
	ASSET_DESC VARCHAR(20) NOT NULL,
	ASSET_VALUE VARCHAR(10) NOT NULL,
	ASSET_AH INT(1) NOT NULL,
	ASSET_MOP INT(1) NOT NULL,
	BANK_ID BIGINT NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT ASSETS_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE ASSETS_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE ASSETS_DATA AUTO_INCREMENT=1000001;

CREATE TABLE PURCHASE_RETURN_DATA (
	ID BIGINT NOT NULL,
	SID VARCHAR(30) NOT NULL,
	INV_REF_NO VARCHAR(25) NOT NULL,
	INV_DATE BIGINT NOT NULL,
	INV_REF_DATE BIGINT NOT NULL,
	CVO_ID BIGINT NOT NULL,
	INV_AMT VARCHAR(10) NOT NULL,
	VBAL_AMOUNT VARCHAR(13) NOT NULL,
	DBAL_AMOUNT VARCHAR(13) NOT NULL,
--	VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL,
	NARRATION VARCHAR(100) NOT NULL,
	CLEARANCE_STATUS INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT PURCHASE_RETURN_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE PURCHASE_RETURN_DATA MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE PURCHASE_RETURN_DATA AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE PURCHASE_RETURN_DATA DROP COLUMN VBAL_AMOUNT_AFTER_DS;

/*
ALTER TABLE PURCHASE_RETURN_DATA ADD COLUMN VBAL_AMOUNT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0 AFTER DBAL_AMOUNT;
UPDATE PURCHASE_RETURN_DATA SET VBAL_AMOUNT_AFTER_DS = VBAL_AMOUNT;
*/

CREATE TABLE PURCHASE_RETURN_DETAILS (
	ID BIGINT NOT NULL,
	PR_REF_ID BIGINT NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	RTN_QTY INT(5) NOT NULL,
	CS_FULLS INT(5) NOT NULL,
	CS_EMPTYS INT(5) NOT NULL,
	DS_FULLS INT(5) NOT NULL,
	DS_EMPTYS INT(5) NOT NULL,
--	DSS_FULLS INT(5) NOT NULL,
--	DSS_EMPTYS INT(5) NOT NULL,	
	UNIT_RATE VARCHAR(10) NOT NULL,
	NET_WEIGHT VARCHAR(10) NOT NULL,
	AMOUNT VARCHAR(13) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
			
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	
	AAMOUNT VARCHAR(13) NOT NULL,
	BANK_ID BIGINT NULL,
	VEHICLE_NO VARCHAR(10) NOT NULL,
	CONSTRAINT PURCHASE_RETURN_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT PURCHASE_RETURN_DETAILS_FK FOREIGN KEY (PR_REF_ID) REFERENCES PURCHASE_RETURN_DATA(ID)
);
ALTER TABLE PURCHASE_RETURN_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE PURCHASE_RETURN_DETAILS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE PURCHASE_RETURN_DETAILS DROP COLUMN DSS_FULLS;
-- ------DROPED------ ALTER TABLE PURCHASE_RETURN_DETAILS DROP COLUMN DSS_EMPTYS;

/*
ALTER TABLE PURCHASE_RETURN_DETAILS ADD COLUMN DSS_FULLS INT(5) NOT NULL DEFAULT 0 AFTER DS_EMPTYS;
ALTER TABLE PURCHASE_RETURN_DETAILS ADD COLUMN DSS_EMPTYS INT(5) NOT NULL DEFAULT 0 AFTER DSS_FULLS;
UPDATE PURCHASE_RETURN_DETAILS SET DSS_FULLS = CS_FULLS, DSS_EMPTYS = CS_EMPTYS;
*/

CREATE TABLE SALES_RETURN_DATA (
	ID BIGINT NOT NULL,
	SR_NO BIGINT(5) NOT NULL,
	INV_REF_NO VARCHAR(25) NOT NULL,
	INV_DATE BIGINT NOT NULL,
	CVO_ID BIGINT NOT NULL,
	PAYMENT_TERMS INT(1) NOT NULL,
	INV_AMT VARCHAR(10) NOT NULL,
	CBAL_AMT VARCHAR(13) NOT NULL,
	DBAL_AMT VARCHAR(13) NOT NULL,
--	CBAL_AMT_AFTER_DS VARCHAR(13) NOT NULL,	
	NARRATION VARCHAR(100) NOT NULL,
	CLEARANCE_STATUS INT(1) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT SALES_RETURN_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE SALES_RETURN_DATA MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE SALES_RETURN_DATA AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE SALES_RETURN_DATA DROP COLUMN CBAL_AMT_AFTER_DS;

-- ALTER TABLE SALES_RETURN_DATA ADD COLUMN CBAL_AMT_AFTER_DS VARCHAR(13) NOT NULL DEFAULT 0 AFTER DBAL_AMT;
-- UPDATE SALES_RETURN_DATA SET CBAL_AMT_AFTER_DS = CBAL_AMT;
ALTER TABLE SALES_RETURN_DATA ADD COLUMN PAYMENT_TERMS INT(1) NOT NULL AFTER CVO_ID;


CREATE TABLE SALES_RETURN_DETAILS (
	ID BIGINT NOT NULL,
	SR_REF_ID BIGINT NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	RTN_QTY INT(5) NOT NULL,
	CS_FULLS INT(5) NOT NULL,
	CS_EMPTYS INT(5) NOT NULL,
	DS_FULLS INT(5) NOT NULL,
	DS_EMPTYS INT(5) NOT NULL,
--	DSS_FULLS INT(5) NOT NULL,
--	DSS_EMPTYS INT(5) NOT NULL,
	UNIT_RATE VARCHAR(10) NOT NULL,
	NET_WEIGHT VARCHAR(10) NOT NULL,
	BANK_ID BIGINT NOT NULL,
	AMOUNT VARCHAR(13) NOT NULL,
	IGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	AAMOUNT VARCHAR(13) NOT NULL,
	CONSTRAINT SALES_RETURN_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT SALES_RETURN_DETAILS_FK FOREIGN KEY (SR_REF_ID) REFERENCES SALES_RETURN_DATA(ID)
);
ALTER TABLE SALES_RETURN_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE SALES_RETURN_DETAILS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE SALES_RETURN_DETAILS DROP COLUMN DSS_FULLS;
-- ------DROPED------ ALTER TABLE SALES_RETURN_DETAILS DROP COLUMN DSS_EMPTYS;

-- ALTER TABLE SALES_RETURN_DETAILS ADD COLUMN DSS_FULLS INT(5) NOT NULL DEFAULT 0 AFTER DS_EMPTYS;
-- ALTER TABLE SALES_RETURN_DETAILS ADD COLUMN DSS_EMPTYS INT(5) NOT NULL DEFAULT 0 AFTER DSS_FULLS;
-- UPDATE SALES_RETURN_DETAILS SET DSS_FULLS = CS_FULLS, DSS_EMPTYS = CS_EMPTYS;
ALTER TABLE SALES_RETURN_DETAILS ADD COLUMN BANK_ID BIGINT NOT NULL AFTER NET_WEIGHT;

CREATE TABLE TV_DATA (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	TV_DATE BIGINT NOT NULL,
	CUSTOMER_NO VARCHAR(20) NOT NULL,
	GST_NO VARCHAR(20) NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	TV_CAT INT(1) NOT NULL,
	TV_AMOUNT VARCHAR(10) NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	R_PROD_CODE INT(4) NOT NULL,
	NO_OF_CYL INT(2) NOT NULL,
	NO_OF_REG INT(2) NOT NULL,
	CS_FULLS INT(5) NOT NULL,
	CS_EMPTYS INT(5) NOT NULL,
	REG_STOCK INT(4) NOT NULL,
	DS_FULLS INT(5) NOT NULL,
	DS_EMPTYS INT(5) NOT NULL,
	DREG_STOCK INT(4) NOT NULL,
--	DSS_FULLS INT(5) NOT NULL,
--	DSS_EMPTYS INT(5) NOT NULL,
--	DSS_REG_STOCK INT(4) NOT NULL,
	CYL_DEPOSIT VARCHAR(8) NOT NULL,
	REG_DEPOSIT VARCHAR(8) NOT NULL,
	IMP_AMOUNT VARCHAR(8) NOT NULL,
	TV_CHARGES_TYPE INT(4) NOT NULL,
	ADMIN_CHARGES VARCHAR(8) NOT NULL,
	IGST_AMOUNT VARCHAR(8) NOT NULL,
	CGST_AMOUNT VARCHAR(8) NOT NULL,
	SGST_AMOUNT VARCHAR(8) NOT NULL,
				
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	
	PAYMENT_TERMS VARCHAR(100) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT TV_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE TV_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE TV_DATA AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE TV_DATA DROP COLUMN DSS_FULLS;
-- ------DROPED------ ALTER TABLE TV_DATA DROP COLUMN DSS_EMPTYS;
-- ------DROPED------ ALTER TABLE TV_DATA DROP COLUMN DSS_REG_STOCK;

-- ALTER TABLE TV_DATA ADD COLUMN DSS_FULLS INT(5) NOT NULL DEFAULT 0 AFTER DREG_STOCK;
-- ALTER TABLE TV_DATA ADD COLUMN DSS_EMPTYS INT(5) NOT NULL DEFAULT 0 AFTER DSS_FULLS;
-- ALTER TABLE TV_DATA ADD COLUMN DSS_REG_STOCK INT(4) NOT NULL DEFAULT 0 AFTER DSS_EMPTYS;
-- UPDATE TV_DATA SET DSS_FULLS=CS_FULLS,DSS_EMPTYS=CS_EMPTYS, DSS_REG_STOCK = REG_STOCK;

--  ALTER TABLE TV_DATA ADD COLUMN OP_BASIC_PRICE VARCHAR(10) NOT NULL AFTER SGST_AMOUNT;
--  ALTER TABLE TV_DATA ADD COLUMN OP_TAXABLE_AMT VARCHAR(10) NOT NULL AFTER OP_BASIC_PRICE;
--	ALTER TABLE TV_DATA ADD COLUMN OP_TOTAL_AMT VARCHAR(10) NOT NULL AFTER OP_TAXABLE_AMT;
--	ALTER TABLE TV_DATA ADD COLUMN OP_IGST_AMT VARCHAR(10) NOT NULL AFTER OP_TOTAL_AMT;
--	ALTER TABLE TV_DATA ADD COLUMN OP_SGST_AMT VARCHAR(10) NOT NULL AFTER OP_IGST_AMT;
--	ALTER TABLE TV_DATA ADD COLUMN OP_CGST_AMT VARCHAR(10) NOT NULL AFTER OP_SGST_AMT;

ALTER TABLE TV_DATA ADD COLUMN TV_CHARGES_TYPE INT(4) NOT NULL AFTER IMP_AMOUNT;


CREATE TABLE RC_DATA (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	RC_DATE BIGINT NOT NULL,
	CUSTOMER_NO VARCHAR(20) NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	RC_AMOUNT VARCHAR(10) NOT NULL,
	PROD_CODE INT(4) NOT NULL,
	NO_OF_CYL INT(3) NOT NULL,
	NO_OF_REG INT(3) NOT NULL,
	REG_STOCK INT(4) NOT NULL,
	DREG_STOCK INT(4) NOT NULL,
--	DSS_REG_STOCK INT(4) NOT NULL,
	CYL_DEPOSIT VARCHAR(8) NOT NULL,
	REG_DEPOSIT VARCHAR(8) NOT NULL,
	DGCC_AMOUNT VARCHAR(8) NOT NULL,
	RC_CHARGES_TYPE INT(4) NOT NULL,
	ADMIN_CHARGES VARCHAR(8) NOT NULL,
	IGST_AMOUNT VARCHAR(8) NOT NULL,
	CGST_AMOUNT VARCHAR(8) NOT NULL,
	SGST_AMOUNT VARCHAR(8) NOT NULL,
	SCGST_AMOUNT VARCHAR(8) NOT NULL,
	SSGST_AMOUNT VARCHAR(8) NOT NULL,
	
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	
	PAYMENT_TERMS VARCHAR(100) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT RC_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE RC_DATA MODIFY COLUMN ID BIGINT(10) AUTO_INCREMENT;
ALTER TABLE RC_DATA AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE RC_DATA DROP COLUMN DSS_REG_STOCK;

-- ALTER TABLE RC_DATA ADD COLUMN DSS_REG_STOCK INT(4) NOT NULL DEFAULT 0 AFTER DREG_STOCK;
-- UPDATE RC_DATA SET DSS_REG_STOCK = REG_STOCK;

--  ALTER TABLE RC_DATA ADD COLUMN OP_BASIC_PRICE VARCHAR(10) NOT NULL AFTER SSGST_AMOUNT;
--  ALTER TABLE RC_DATA ADD COLUMN OP_TAXABLE_AMT VARCHAR(10) NOT NULL AFTER OP_BASIC_PRICE;
--	ALTER TABLE RC_DATA ADD COLUMN OP_TOTAL_AMT VARCHAR(10) NOT NULL AFTER OP_TAXABLE_AMT;
--	ALTER TABLE RC_DATA ADD COLUMN OP_IGST_AMT VARCHAR(10) NOT NULL AFTER OP_TOTAL_AMT;
--	ALTER TABLE RC_DATA ADD COLUMN OP_SGST_AMT VARCHAR(10) NOT NULL AFTER OP_IGST_AMT;
--	ALTER TABLE RC_DATA ADD COLUMN OP_CGST_AMT VARCHAR(10) NOT NULL AFTER OP_SGST_AMT;

 ALTER TABLE RC_DATA ADD COLUMN RC_CHARGES_TYPE INT(4) NOT NULL AFTER DGCC_AMOUNT;


CREATE TABLE NCDBCRCTV_INVOICES (
	ID BIGINT NOT NULL,
	SR_NO VARCHAR(30) NOT NULL,
	BOM_ID BIGINT NOT NULL,
	CONN_TYPE INT(1) NOT NULL,
	INV_DATE BIGINT NOT NULL,
	CUSTOMER_NO VARCHAR(20) NOT NULL,
	STAFF_ID BIGINT NOT NULL,
	NO_OF_CONNS INT(3) NOT NULL,
	CASH_AMOUNT VARCHAR(10) NOT NULL,
	ONLINE_AMOUNT VARCHAR(10) NOT NULL,
	DEP_AMOUNT VARCHAR(10) NOT NULL,
	INV_AMOUNT VARCHAR(10) NOT NULL,
    BANK_ID BIGINT NOT NULL,
    DISCOUNT VARCHAR(8) NOT NULL,
	CREATED_BY    	BIGINT(10) NULL,
	CREATED_DATE  	BIGINT NULL,
	MODIFIED_BY   	BIGINT(10) NULL,
	MODIFIED_DATE 	BIGINT NULL,
	VERSION       	INT(1) NULL,
	DELETED       	INT(1) NULL,
	CONSTRAINT NCDBCRCTV_INVOICES_PK PRIMARY KEY (ID)
);
ALTER TABLE NCDBCRCTV_INVOICES MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE NCDBCRCTV_INVOICES AUTO_INCREMENT=1000001;

-- ALTER TABLE NCDBCRCTV_INVOICES ADD COLUMN DISCOUNT VARCHAR(8) NOT NULL AFTER BANK_ID;

CREATE TABLE NCDBCRCTV_INVOICES_DETAILS (
	ID BIGINT NOT NULL,
	INV_ID BIGINT NOT NULL,
	PROD_CODE BIGINT NOT NULL,
	C_STOCK INT(4) NOT NULL,
	E_STOCK INT(4) NOT NULL,
	DC_STOCK INT(4) NOT NULL,
	DE_STOCK INT(4) NOT NULL,
--	DSC_STOCK INT(4) NOT NULL,
--	DSE_STOCK INT(4) NOT NULL,
	QUANTITY INT(5) NOT NULL,
	UNIT_RATE VARCHAR(8) NOT NULL,
	DISC_UNIT_RATE VARCHAR(8) NOT NULL,
	BASIC_PRICE VARCHAR(10) NOT NULL,
	DEPOSIT_AMOUNT VARCHAR(8) NOT NULL,
	GSTP VARCHAR(5) NOT NULL,
	SGST_AMOUNT VARCHAR(10) NOT NULL,
	CGST_AMOUNT VARCHAR(10) NOT NULL,
	
	OP_TAXABLE_AMT VARCHAR(10) NOT NULL,
	OP_TOTAL_AMT VARCHAR(10) NOT NULL,
	OP_IGST_AMT VARCHAR(10) NOT NULL,
	OP_SGST_AMT VARCHAR(10) NOT NULL,
	OP_CGST_AMT VARCHAR(10) NOT NULL,
	
	PRODUCT_AMOUNT VARCHAR(10) NOT NULL,
	CONSTRAINT NCDBCRCTV_INVOICES_DETAILS_PK PRIMARY KEY (ID),
	CONSTRAINT NCDBCRCTV_INVOICES_DETAILS_FK FOREIGN KEY (INV_ID) REFERENCES NCDBCRCTV_INVOICES(ID)
);
ALTER TABLE NCDBCRCTV_INVOICES_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE NCDBCRCTV_INVOICES_DETAILS AUTO_INCREMENT=1000001;

-- ------DROPED------ ALTER TABLE NCDBCRCTV_INVOICES_DETAILS DROP COLUMN DSC_STOCK;
-- ------DROPED------ ALTER TABLE NCDBCRCTV_INVOICES_DETAILS DROP COLUMN DSE_STOCK;

/*
ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN DSC_STOCK INT(4) NOT NULL DEFAULT 0 AFTER DE_STOCK;
ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN DSE_STOCK INT(4) NOT NULL DEFAULT 0 AFTER DSC_STOCK;
UPDATE NCDBCRCTV_INVOICES_DETAILS SET DSC_STOCK=C_STOCK , DSE_STOCK=E_STOCK;
*/

--  ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN OP_BASIC_PRICE VARCHAR(10) NOT NULL AFTER CGST_AMOUNT;
--  ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN OP_TAXABLE_AMT VARCHAR(10) NOT NULL AFTER OP_BASIC_PRICE;
--	ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN OP_TOTAL_AMT VARCHAR(10) NOT NULL AFTER OP_TAXABLE_AMT;
--	ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN OP_IGST_AMT VARCHAR(10) NOT NULL AFTER OP_TOTAL_AMT;
--	ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN OP_SGST_AMT VARCHAR(10) NOT NULL AFTER OP_IGST_AMT;
--	ALTER TABLE NCDBCRCTV_INVOICES_DETAILS ADD COLUMN OP_CGST_AMT VARCHAR(10) NOT NULL AFTER OP_SGST_AMT;


CREATE TABLE AGENCYS_PARTNERS
( 
 ID BIGINT NOT NULL,
 PARTNER_NAME VARCHAR(25) NOT NULL,
 PAN VARCHAR(10) NOT NULL,
 SHARE_PERCENT VARCHAR(5) NOT NULL,
 OPENING_BALANCE VARCHAR(13) NOT NULL,
 STATUS INT(1) NOT NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT AGENCYS_PARTNERS_PK PRIMARY KEY (ID)
);
ALTER TABLE AGENCYS_PARTNERS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE AGENCYS_PARTNERS AUTO_INCREMENT=1000001;

CREATE TABLE AGENCYS_PARTNERS_TRANXS
( 
 ID BIGINT NOT NULL,
 PARTNER_ID BIGINT NOT NULL,
 BANK_ID BIGINT NOT NULL,
 TRANX_DATE BIGINT NOT NULL,
 TRANX_TYPE INT(1) NOT NULL,
 TRANX_AMOUNT VARCHAR(13) NOT NULL,
 REMARKS VARCHAR(50) NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT AGENCYS_PARTNERS_TRANXS_PK PRIMARY KEY (ID)
);
ALTER TABLE AGENCYS_PARTNERS_TRANXS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE AGENCYS_PARTNERS_TRANXS AUTO_INCREMENT=1000001;

CREATE TABLE DEPRECIATION_REPORTS (
 ID BIGINT NOT NULL,
 FYV INT(4) NOT NULL,
 O_AMT VARCHAR(18) NOT NULL,
 P_AMT VARCHAR(18) NOT NULL,
 C_AMT VARCHAR(18) NOT NULL,
 D_AMT VARCHAR(18) NOT NULL,
 STATUS INT(1) NOT NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT DEPRECIATION_REPORTS_PK PRIMARY KEY (ID)
);
ALTER TABLE DEPRECIATION_REPORTS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE DEPRECIATION_REPORTS AUTO_INCREMENT=1000001;

CREATE TABLE DEPRECIATION_REPORTS_DETAILS (
 ID BIGINT NOT NULL,
 DR_ID INT(4) NOT NULL,
 AT_ID INT(3) NOT NULL,
 NP_AMT VARCHAR(18) NOT NULL,
 NC_AMT VARCHAR(18) NOT NULL,
 ND_AMT VARCHAR(18) NOT NULL,
 CONSTRAINT DEPRECIATION_REPORTS_DETAILS_PK PRIMARY KEY (ID)
);
ALTER TABLE DEPRECIATION_REPORTS_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE DEPRECIATION_REPORTS_DETAILS AUTO_INCREMENT=1000001;

CREATE TABLE CAPITAL_ACCOUNT_REPORTS (
 ID BIGINT NOT NULL,
 FYV INT(4) NOT NULL,
 IS_NEW INT(1) NOT NULL,
 O_AMT VARCHAR(18) NOT NULL,
 PO_AMT VARCHAR(18) NOT NULL,
 I_AMT VARCHAR(18) NOT NULL,
 W_AMT VARCHAR(18) NOT NULL,
 C_AMT VARCHAR(18) NOT NULL,
 STATUS INT(1) NOT NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT CAPITAL_ACCOUNT_REPORTS_PK PRIMARY KEY (ID)
);
ALTER TABLE CAPITAL_ACCOUNT_REPORTS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE CAPITAL_ACCOUNT_REPORTS AUTO_INCREMENT=1000001;

CREATE TABLE PROFIT_AND_LOSS_ACCOUNTS_DATA (
 ID BIGINT NOT NULL,
 FYV INT(4) NOT NULL,
 STATUS INT(1) NOT NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT PROFIT_AND_LOSS_ACCOUNTS_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE PROFIT_AND_LOSS_ACCOUNTS_DATA MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE PROFIT_AND_LOSS_ACCOUNTS_DATA AUTO_INCREMENT=1000001;

CREATE TABLE PROFIT_AND_LOSS_ACCOUNTS_DETAILS (
 ID BIGINT NOT NULL,
 PL_ID BIGINT NOT NULL,
 OSV_AMT VARCHAR(15) DEFAULT '0.00',
 CSV_AMT VARCHAR(15) DEFAULT '0.00',
 PV_AMT VARCHAR(15) DEFAULT '0.00',
 SV_AMT VARCHAR(15) DEFAULT '0.00',
 OI_AMT VARCHAR(15) DEFAULT '0.00',
 GP_AMT VARCHAR(15) DEFAULT '0.00',
 FO_AMT VARCHAR(15) DEFAULT '0.00',
 FI_AMT VARCHAR(15) DEFAULT '0.00',
 UC_AMT VARCHAR(15) DEFAULT '0.00',
 IL_AMT VARCHAR(15) DEFAULT '0.00',
 SP_AMT VARCHAR(15) DEFAULT '0.00',
 TC_AMT VARCHAR(15) DEFAULT '0.00',
 MS_AMT VARCHAR(15) DEFAULT '0.00',
 RN_AMT VARCHAR(15) DEFAULT '0.00',
 BP_AMT VARCHAR(15) DEFAULT '0.00',
 SW_AMT VARCHAR(15) DEFAULT '0.00',
 BC_AMT VARCHAR(15) DEFAULT '0.00',
 DP_AMT VARCHAR(15) DEFAULT '0.00',
 NP_AMT VARCHAR(15) DEFAULT '0.00',
 CONSTRAINT PROFIT_AND_LOSS_ACCOUNTS_DETAILS_PK PRIMARY KEY (ID),
 CONSTRAINT PROFIT_AND_LOSS_ACCOUNTS_DETAILS_FK FOREIGN KEY (PL_ID) REFERENCES PROFIT_AND_LOSS_ACCOUNTS_DATA(ID)
);
ALTER TABLE PROFIT_AND_LOSS_ACCOUNTS_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE PROFIT_AND_LOSS_ACCOUNTS_DETAILS AUTO_INCREMENT=1000001;


CREATE TABLE BALANCE_SHEET_DATA (
 ID BIGINT NOT NULL,
 FYV INT(4) NOT NULL,
 STATUS INT(1) NOT NULL,
 REMARKS VARCHAR(100) NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT BALANCE_SHEET_DATA_PK PRIMARY KEY (ID)
);
ALTER TABLE BALANCE_SHEET_DATA MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE BALANCE_SHEET_DATA AUTO_INCREMENT=1000001;

CREATE TABLE BALANCE_SHEET_DETAILS (
 ID BIGINT NOT NULL,
 BS_ID BIGINT NOT NULL,
 CAOB_AMT VARCHAR(18) NOT NULL,
 CANI_AMT VARCHAR(18) NOT NULL,
 CANW_AMT VARCHAR(18) NOT NULL,
 CACB_AMT VARCHAR(18) NOT NULL,
 PLNP_AMT VARCHAR(18) NOT NULL,
 CATB_AMT VARCHAR(18) NOT NULL,
 FAOB_AMT VARCHAR(18) NOT NULL,
 FANP_AMT VARCHAR(18) NOT NULL,
 FANS_AMT VARCHAR(18) NOT NULL,
 FADP_AMT VARCHAR(18) NOT NULL,
 FACB_AMT VARCHAR(18) NOT NULL,
 CACS_AMT VARCHAR(18) NOT NULL,
 CLSC_AMT VARCHAR(18) NOT NULL,
 CASD_AMT VARCHAR(18) NOT NULL,
 CALA_AMT VARCHAR(18) NOT NULL,
 CACH_AMT VARCHAR(18) NOT NULL,
 CADP_AMT VARCHAR(18) NOT NULL,
 CARS_AMT VARCHAR(18) NOT NULL,
 CABC_AMT VARCHAR(18) NOT NULL,
 SLTB_AMT VARCHAR(18) NOT NULL,
 ULFR_AMT VARCHAR(18) NOT NULL,
 PROV_AMT VARCHAR(18) NOT NULL,
 FYTL_AMT VARCHAR(18) NOT NULL,
 FYTA_AMT VARCHAR(18) NOT NULL,
 CONSTRAINT BALANCE_SHEET_DETAILS_PK PRIMARY KEY (ID),
 CONSTRAINT BALANCE_SHEET_DETAILS_FK FOREIGN KEY (BS_ID) REFERENCES BALANCE_SHEET_DATA(ID)
);
ALTER TABLE BALANCE_SHEET_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE BALANCE_SHEET_DETAILS AUTO_INCREMENT=1000001;
