CREATE TABLE GST_PAYMENTS_DATA (
 ID BIGINT NOT NULL,
 MONTH INT(2) NOT NULL,
 YEAR INT(4) NOT NULL,
 SET_OFF_DATE BIGINT NOT NULL,
 PAY_OFF_DATE BIGINT NOT NULL,
 STATUS INT(1) NOT NULL, 
 CREDITORS_IGST VARCHAR(10) NOT NULL,
 CREDITORS_SGST VARCHAR(10) NOT NULL,
 CREDITORS_CGST VARCHAR(10) NOT NULL,
 LIABILITY_IGST VARCHAR(10) NOT NULL,
 LIABILITY_SGST VARCHAR(10) NOT NULL,
 LIABILITY_CGST VARCHAR(10) NOT NULL,
 CASH_SGST VARCHAR(10) NOT NULL,
 CASH_CGST VARCHAR(10) NOT NULL,
 CREATED_BY    	BIGINT(10) NULL,
 CREATED_DATE  	BIGINT NULL,
 MODIFIED_BY   	BIGINT(10) NULL,
 MODIFIED_DATE 	BIGINT NULL,
 VERSION       	INT(1) NULL,
 DELETED       	INT(1) NULL,
 CONSTRAINT GST_PAYMENTS_DATA_PK PRIMARY KEY (ID)
);
GO
ALTER TABLE GST_PAYMENTS_DATA MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
GO
ALTER TABLE GST_PAYMENTS_DATA AUTO_INCREMENT=1000001;
GO

select * from GST_PAYMENTS_DATA;
/* TRUNCATE GST_PAYMENTS_DATA; */

ALTER TABLE GST_PAYMENTS_DATA ADD COLUMN PAY_OFF_DATE BIGINT NOT NULL AFTER SET_OFF_DATE;

----------------------------------------------------------------------------------------------------------------------
/* GST_PAYMENT_DETAILS AND GST_PAYMENTS_DATA TABLES ARE NOT RELATED AS LIKE INVOICE AND DETAILS*/

/* GST_PAYMENT_DETAILS */
CREATE TABLE GST_PAYMENT_DETAILS(
 ID BIGINT NOT NULL,
 PAYMENT_ID BIGINT NOT NULL,
 MONTH INT(2) NOT NULL,
 YEAR INT(4) NOT NULL,
 PSTATUS INT(1) NOT NULL,   /* 1- CREDIT TO THIS ACCT. I.e, from PAYMENTS. 2- DEBIT to this GST_PAYMENT_DETAILS ACCT I.e, from GSTR3 when pay-off is done. */
 PDATE BIGINT NOT NULL,
 TAX_TYPE INT(1) NOT NULL,       /* 1-GST AMOUNT, 2-INCOME TAX  */
 GST_AMOUNT VARCHAR(10) NOT NULL,
 TOTAL_GST_AMOUNT VARCHAR(10) NOT NULL,
 DT_GST_AMOUNT VARCHAR(10) NOT NULL,      /* TOTAL GST AMOUNT when a record is deleted  */
 DS_TOTAL_GST_AMOUNT VARCHAR(10) NOT NULL,
 FINAL_GST_AMOUNT VARCHAR(10) NOT NULL,	  /* FINAL UPDATED GST AMOUNT  */
 INCOMETAX_AMOUNT VARCHAR(10) NOT NULL,
 CREATED_BY            BIGINT(10) NULL,
 CREATED_DATE          BIGINT NULL,
 MODIFIED_BY           BIGINT(10) NULL,
 MODIFIED_DATE         BIGINT NULL,
 VERSION               INT(1) NULL,
 DELETED               INT(1) NULL,
 CONSTRAINT GST_PAYMENT_DETAILS_PK PRIMARY KEY (ID)
);
ALTER TABLE GST_PAYMENT_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE GST_PAYMENT_DETAILS AUTO_INCREMENT=1000001;

----ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN DS_TOTAL_GST_AMOUNT VARCHAR(10) NOT NULL AFTER DT_GST_AMOUNT;
----UPDATE GST_PAYMENT_DETAILS SET DS_TOTAL_GST_AMOUNT = TOTAL_GST_AMOUNT;

/*
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN PAYMENT_ID BIGINT NOT NULL AFTER ID;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN PSTATUS INT(1) NOT NULL AFTER YEAR;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN TOTAL_GST_AMOUNT VARCHAR(10) NOT NULL AFTER GST_AMOUNT;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN DT_GST_AMOUNT VARCHAR(10) NOT NULL AFTER TOTAL_GST_AMOUNT;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN FINAL_GST_AMOUNT VARCHAR(10) NOT NULL AFTER DT_GST_AMOUNT;
*/

/* UPDATE GST_PAYMENT_DETAILS SET FINAL_GST_AMOUNT = 0 WHERE CREATED_BY = 3333333333 */

DROP TABLE GST_PAYMENT_DETAILS;
SELECT * FROM GST_PAYMENT_DETAILS;
/* TRUNCATE GST_PAYMENT_DETAILS; */

SELECT * FROM GST_PAYMENT_DETAILS WHERE CREATED_BY = 1111111111 AND MONTH = 5 AND YEAR = 2018 AND TAX_TYPE = 1 ORDER BY CREATED_DATE DESC;


---------------------------------------------------------------------------------------------------------------------

/* GST_PAYMENT_DETAILS AND GST_PAYMENTS_DATA TABLES ARE NOT RELATED AS LIKE INVOICE AND DETAILS*/

/*
/* GST_PAYMENT_DETAILS */
CREATE TABLE GST_PAYMENT_DETAILS(
 ID BIGINT NOT NULL,
 MONTH INT(2) NOT NULL,
 YEAR INT(4) NOT NULL,
 PDATE BIGINT NOT NULL,          /* IF STATUS=1 THEN THIS IS PAY-OFF DATE ELSE IF 0 THEN TRANSACTION DATE  */
 STATUS INT(1) NOT NULL,         /* STATUS = 0 --> PAYMENT TO GSTACCT , 1 --> PAY-OFFF     */
 TAX_TYPE INT(1) NOT NULL,       /* 1-CGST AMOUNT, 2-SGST AMOUNT, 3- INCOME TAX, 4-IGST AMOUNT  */
 IGST_AMOUNT VARCHAR(10) NOT NULL,
 SGST_AMOUNT VARCHAR(10) NOT NULL,
 CGST_AMOUNT VARCHAR(10) NOT NULL,
 TOTAL_GST_AMOUNT VARCHAR(10) NOT NULL,
 INCOMETAX_AMOUNT VARCHAR(10) NOT NULL,
 CREATED_BY            BIGINT(10) NULL,
 CREATED_DATE          BIGINT NULL,
 MODIFIED_BY           BIGINT(10) NULL,
 MODIFIED_DATE         BIGINT NULL,
 VERSION               INT(1) NULL,
 DELETED               INT(1) NULL,
 CONSTRAINT GST_PAYMENT_DETAILS_PK PRIMARY KEY (ID)
);
ALTER TABLE GST_PAYMENT_DETAILS MODIFY COLUMN ID BIGINT AUTO_INCREMENT;
ALTER TABLE GST_PAYMENT_DETAILS AUTO_INCREMENT=1000001;

/* ALTER TABLE GST_PAYMENT_DETAILS CHANGE PAY_OFF_DATE PDATE BIGINT;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN INCOMETAX_AMOUNT VARCHAR(10) NOT NULL AFTER TOTAL_GST_AMOUNT;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN TAX_TYPE INT(1) NOT NULL AFTER PDATE;
ALTER TABLE GST_PAYMENT_DETAILS ADD COLUMN STATUS INT(1) NOT NULL AFTER PDATE; */

SELECT * FROM GST_PAYMENT_DETAILS;
/* TRUNCATE GST_PAYMENT_DETAILS; */

*/

---------------------------------------------------------------------------------------------------------------

