/*
* INDIAN STATES AND UTS STATIC DATA
*/

/*
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('AP','ANDHRA PRADESH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('AR','ARUNACHAL PRADESH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('AS','ASSAM');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('BR','BIHAR');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('CG','CHHATTISHGARH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('GA','GOA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('GJ','GUJARAT');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('HR','HARAYANA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('HP','HIMACHAL PRADESH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('JK','JAMMU AND KASHMIR');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('JH','JHARKHAND');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('KA','KARNATAKA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('KL','KERALA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('MP','MADHYA PRADESH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('MH','MAHARASHTRA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('MN','MANIPUR');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('ML','MEGHALAYA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('MZ','MIZORAM');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('NL','NAGALAND');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('OD','ODISHA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('PB','PUNJAB');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('RJ','RAJASTHAN');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('SK','SIKKIM');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('TN','TAMILNADU');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('TS','TELANGANA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('TR','TRIPURA');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('UP','UTTAR PRADESH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('UK','UTHARAKHAND');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('WB','WEST BENGAL');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('AN','ANDAMAN AND NICOBAR ISLANDS');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('CH','CHANDIGARH');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('DN','DADAR AND NAGAR HAVELI');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('DD','DAMAN AND DIU');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('LD','LAKSHADWEEP');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('DL','DELHI');
GO
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('PY','PUDUCHERRY');
GO
*/

INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('01','JAMMU & KASHMIR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('02','HIMACHAL PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('03','PUNJAB');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('04','CHANDIGARH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('05','UTTARAKHAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('06','HARYANA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('07','DELHI');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('08','RAJASTHAN');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('09','UTTAR PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('10','BIHAR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('11','SIKKIM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('12','ARUNACHAL PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('13','NAGALAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('14','MANIPUR');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('15','MIZORAM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('16','TRIPURA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('17','MEGHALAYA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('18','ASSAM');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('19','WEST BENGAL');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('20','JHARKHAND');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('21','ODISHA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('22','CHHATTISGARH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('23','MADHYA PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('24','GUJARAT');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('25','DAMAN & DIU');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('26','DADRA & NAGAR HAVELI');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('27','MAHARASHTRA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('29','KARNATAKA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('30','GOA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('31','LAKSHDWEEP');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('32','KERALA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('33','TAMIL NADU');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('34','PONDICHERRY');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('35','ANDAMAN & NICOBAR ISLANDS');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('36','TELANGANA');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('37','ANDHRA PRADESH');
INSERT INTO STATES_AND_UT_ENUM (STATE_OR_UT_CODE,STATE_OR_UT_NAME) VALUES ('97','OTHER TERRITORY');


/**
 * STATUTORY_MASTER_ENUM SEED DATA
 */
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (1,'DISTRIBUTORSHIP AGREEMENT');
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (2,'EXPLOSIVE LICENCE');
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (3,'CIVIL SUPPLY LICENCE');
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (4,'PLATFORM WEIGHING SCALE');
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (5,'PORTABLE WEIGHING SCALE');
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (6,'FIRE EXTINGHUISHER');
INSERT INTO STATUTORY_MASTER_ENUM (ID, ITEM) VALUES (7,'LABOUR LICENCE');

/*
* PRODUCT_CATEGORY_MASTER SEED DATA
*/
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (1,'109','DOMESTIC','5 KG SUB CYLINDER',1,0);

-- INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (2,'036','DOMESTIC','14.2 KG SUB CYLINDER',1,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (2,'036','DOMESTIC','14.2 KG SUB CYLINDER',1,1);

INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (3,'036','DOMESTIC','14.2 KG NS CYLINDER',1,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (4,'027','COMMERCIAL','5 KG FTL CYLINDER',2,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (5,'064','COMMERCIAL','19 KG NDNE CYLINDER',2,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (6,'064','COMMERCIAL','19 KG CUTTING GAS CYLINDER',2,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (7,'122','COMMERCIAL','35 KG NDNE CYLINDER',2,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (8,'042','COMMERCIAL','47.5 KG NDNE CYLINDER',2,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (9,'149','COMMERCIAL','450 KG NDNE CYLINDERS',2,0);
-- INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (9,'149','COMMERCIAL','450 KG SUMO CYLINDERS',2,0);
-- UPDATE PRODUCT_CATEGORY_DATA SET CAT_DESC = "450 KG NDNE CYLINDER" WHERE ID=9;
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (10,'042NS','REGULATOR','SC TYPE',3,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (11,'098','REGULATOR','MF ELECTRONIC',3,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (12,'098S','REGULATOR','FTL',3,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (13,'ARB01','ARB','STOVE',4,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (14,'ARB02','ARB','SURAKSHA',4,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (15,'ARB03','ARB','LIGHTER',4,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (16,'ARB04','ARB','KITCHENWARE',4,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (17,'ARB05','ARB','OTHERS',4,0);

-- DELETE FROM PRODUCT_CATEGORY_DATA WHERE ID = 2;

/*
 * INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (12,'098S','REGULATOR','MF ANALOG',3,0);

INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (18,'SR001','SERVICE','NC ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (19,'SR002','SERVICE','DBC ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (20,'SR003','SERVICE','RECONNECTION CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (21,'SR004','SERVICE','TV ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (22,'SR005','SERVICE','MANDATORY INSP',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (23,'SR006','SERVICE','HOTPLATE INSP',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (24,'SR007','SERVICE','DGCC BOOK ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (25,'SR008','SERVICE','MECHANIC VISIT (PAID)',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (26,'SR009','SERVICE','INSTALLATION CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (27,'SR010','SERVICE','ADMIN CHARGES FOR BPL CONNECTION',5,0);
*/

/*
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (18,'SR001','SERVICE','ADMIN CHARGES - REG',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (19,'SR002','SERVICE','RECONNECTION CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (20,'SR003','SERVICE','TV ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (21,'SR004','SERVICE','MANDATORY INSP',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (22,'SR005','SERVICE','HOTPLATE INSP',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (23,'SR006','SERVICE','DGCC BOOK ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (24,'SR007','SERVICE','MECHANIC VISIT (PAID)',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (25,'SR008','SERVICE','INSTALLATION CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (26,'SR009','SERVICE','ADMIN CHARGES FOR BPL CONNECTION',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (27,'SR010','SERVICE','DGCC BOOK ADMIN CHARGES FOR BPL CONNECTION',5,0);
*/


INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (18,'SR001','SERVICE','ADMIN CHARGES - REG',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (19,'SR002','SERVICE','RECONNECTION CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (20,'SR003','SERVICE','TV ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (21,'SR004','SERVICE','MANDATORY INSP',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (22,'SR005','SERVICE','HOTPLATE INSP',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (23,'SR006','SERVICE','DGCC BOOK ADMIN CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (24,'SR007','SERVICE','MECHANIC VISIT (PAID)',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (25,'SR008','SERVICE','INSTALLATION CHARGES',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (26,'SR009','SERVICE','ADMIN CHARGES FOR BPL CONNECTION',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (27,'SR010','SERVICE','DGCC BOOK ADMIN CHARGES FOR BPL CONNECTION',5,0);
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (28,'SR011','SERVICE','TV CYLINDER COLLECTION CHARGES FROM CUSTOMER DOORSTEP',5,0); -- TV CHARGES(100/-) + 150/- = 250/-
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (29,'SR012','SERVICE','NILL',5,0); -- 0/- CHARGES - APPLICABLE IN RC AND TV

INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (30,'SR013','SERVICE','INSTALLATION CHARGES FOR UJJWALA',5,0); -- UJJWALA CHARGES(75/-) + 0 GST/- = 250/-
INSERT INTO PRODUCT_CATEGORY_DATA (ID,CAT_CODE,CAT_NAME,CAT_DESC,CAT_TYPE,DELETED) VALUES (31,'SR014','SERVICE','DGCC CHARGES FOR UJJWALA',5,0); -- DGCC CHARGES 25 -0 GST

-- ALTER TABLE PRODUCT_CATEGORY_DATA MODIFY COLUMN CAT_DESC VARCHAR(60) NOT NULL;
-- select * from PRODUCT_CATEGORY_DATA;
-- desc PRODUCT_CATEGORY_DATA;

-- update PRODUCT_CATEGORY_DATA set CAT_DESC= "INSTALLATION CHARGES FOR UJJWALA" where id = 30;
-- update PRODUCT_CATEGORY_DATA set CAT_DESC= "DGCC CHARGES FOR UJJWALA" where id = 31;


/*
 * Services Data
 */
/*
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000001,18,50.00,9.00,'SAC001',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000002,19,50.00,9.00,'SAC002',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000003,20,50.00,9.00,'SAC003',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000004,21,50.00,9.00,'SAC004',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000005,22,150.00,27.00,'SAC005',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000006,23,250.00,45.00,'SAC006',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000007,24,50.00,9.00,'SAC007',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000008,25,150.00,27.00,'SAC008',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000009,26,100.00,18.00,'SAC009',1498890600000,0,0,0,0,0,0);
GO
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000010,27,50.00,9.00,'SAC010',1498890600000,0,0,0,0,0,0);
GO
*/

/*
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000001,18,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000002,19,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000003,20,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000004,21,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000005,22,150.00,27.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000006,23,250.00,45.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000007,24,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000008,25,150.00,27.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000009,26,100.00,18.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000010,27,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
*/

/*
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000001,18,75.00,13.50,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000002,19,75.00,13.50,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000003,20,0.00,0.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000004,21,150.00,27.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000005,22,250.00,45.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000006,23,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000007,24,150.00,27.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000008,25,100.00,18.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000009,26,75.00,13.50,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000010,27,25.00,4.50,'998399',1498890600000,0,0,0,0,0,0);
*/


INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000001,18,75.00,13.50,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000002,19,100.00,18.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000003,20,100.00,18.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000004,21,150.00,27.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000005,22,250.00,45.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000006,23,50.00,9.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000007,24,150.00,27.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000008,25,100.00,18.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000009,26,75.00,13.50,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000010,27,25.00,4.50,'998399',1498890600000,0,0,0,0,0,0);

INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000011,28,250.00,45.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED) 
	VALUES (1000012,29,0.00,0.00,'998399',1498890600000,0,0,0,0,0,0);

INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED)
        VALUES (1000013,30,75.00,0.00,'998399',1498890600000,0,0,0,0,0,0);
INSERT INTO SERVICES_DATA (ID,PROD_CODE,PROD_CHARGES,GST_AMT,SAC_CODE,EFFECTIVE_DATE,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,VERSION,DELETED)
        VALUES (1000014,31,25.00,0.00,'998399',1498890600000,0,0,0,0,0,0);

--	SELECT * FROM SERVICES_DATA;

/*
 * DEP_PERCENT_ENUM
 */

INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (141,'LAND',0,0);
INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (142,'BUILDING',10,5);
INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (143,'PLANT AND MACHINARY',0,0);
INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (144,'FURNITURE AND FIXTURES',10,5);
INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (145,'MOTAR VEHICLES',30,15);
INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (146,'COMPUTERS AND PRINTERS',50,25);
INSERT INTO DEP_PERCENT_ENUM (ID,ITEM,PERCENT_FY,PERCENT_HY) VALUES (147,'OTHER MOVABLE ASSETS',0,0);

